export const REQUEST_ACCOUNT_LIST = 'REQUEST_ACCOUNT_LIST';
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
export const LOAD_ACCOUNTS_SUCCESS = 'LOAD_ACCOUNTS_SUCCESS';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UNDO_DELETE_ACCOUNT = 'UNDO_DELETE_ACCOUNT';
export const REMOVE_DELETED_ACCOUNT = 'REMOVE_DELETED_ACCOUNT';
