export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const RECEIVE_NEW_CATEGORY = 'RECEIVE_NEW_CATEGORY';
export const UNDO_DELETE_CATEGORY = 'UNDO_DELETE_CATEGORY';
export const RECEIVE_UPDATED_CATEGORY = 'RECEIVE_UPDATED_CATEGORY';
