export const LOAD_INVESTMENTS = 'LOAD_INVESTMENTS';
export const LOAD_INVESTMENTS_SUCCESS = 'LOAD_INVESTMENTS_SUCCESS';
export const PURCHASE_INVESTMENT_SUCCESS = 'PURCHASE_INVESTMENT_SUCCESS';
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
export const UNDO_DELETE_INVESTMENT = 'UNDO_DELETE_INVESTMENT';
export const UPDATE_INVESTMENT_SUCCESS = 'UPDATE_INVESTMENT_SUCCESS';