export const LOAD_INVESTMENTS = 'LOAD_INVESTMENTS';
export const LOAD_INVESTMENTS_SUCCESS = 'LOAD_INVESTMENTS_SUCCESS';
export const CREATE_INVESTMENT_SUCCESS = 'CREATE_INVESTMENT_SUCCESS';
export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
export const UNDO_DELETE_INVESTMENT = 'UNDO_DELETE_INVESTMENT';
export const UPDATE_INVESTMENT_SUCCESS = 'UPDATE_INVESTMENT_SUCCESS';
export const MAKE_CORRECTING_ENTRIES_SUCCESS = 'MAKE_CORRECTING_ENTRIES_SUCCESS';