export const LOAD_INVOICES = 'LOAD_INVOICES';
export const LOAD_INVOICES_SUCCESS = 'LOAD_INVOICES_SUCCESS';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const UNDO_DELETE_INVOICE = 'UNDO_DELETE_INVOICE';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const LOAD_INVOICE_SUCCESS = 'LOAD_INVOICE_SUCCESS';
export const EMAIL_INVOICE_SUCCESS = 'EMAIL_INVOICE_SUCCESS';