export const LOAD_NET_WORTH_REPORT = 'LOAD_NET_WORTH_REPORT';
export const LOAD_NET_WORTH_REPORT_SUCCESS = 'LOAD_NET_WORTH_REPORT_SUCCESS';
export const LOAD_EXPENSES_BY_CATEGORY_REPORT = 'LOAD_EXPENSES_BY_CATEGORY_REPORT';
export const LOAD_EXPENSES_BY_CATEGORY_REPORT_SUCCESS = 'LOAD_EXPENSES_BY_CATEGORY_REPORT_SUCCESS';