export const LOAD_NET_WORTH_REPORT = 'LOAD_NET_WORTH_REPORT';
export const LOAD_NET_WORTH_REPORT_SUCCESS = 'LOAD_NET_WORTH_REPORT_SUCCESS';
export const LOAD_EXPENSES_BY_CATEGORY_REPORT = 'LOAD_EXPENSES_BY_CATEGORY_REPORT';
export const LOAD_EXPENSES_BY_CATEGORY_REPORT_SUCCESS = 'LOAD_EXPENSES_BY_CATEGORY_REPORT_SUCCESS';
export const LOAD_INCOME_REPORT = 'LOAD_INCOME_REPORT ';
export const LOAD_INCOME_REPORT_SUCCESS = 'LOAD_INCOME_REPORT_SUCCESS';
export const LOAD_DASHBOARD_STATS = 'LOAD_DASHBOARD_STATS';
export const LOAD_DASHBOARD_STATS_SUCCESS = 'LOAD_DASHBOARD_STATS_SUCCESS';